# Generated by Django 4.1.3 on 2023-02-17 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('discription', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Statuses',
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/sub/')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.taskstatus')),
            ],
            options={
                'verbose_name': 'sub task',
                'verbose_name_plural': 'Sub tasks',
            },
        ),
        migrations.CreateModel(
            name='MainTask',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('discription', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/main/')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.taskstatus')),
                ('sub_task', models.ManyToManyField(blank=True, null=True, to='tasks.subtask')),
            ],
            options={
                'verbose_name': 'Main task',
                'verbose_name_plural': 'Main tasks',
            },
        ),
    ]
