# Generated by Django 4.1.3 on 2023-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
