# Generated by Django 4.1.3 on 2023-02-17 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0003_alter_maintask_participants_alter_maintask_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('discription', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/main/')),
                ('participants', models.ManyToManyField(blank=True, related_name='project_participants', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_participants', to='tasks.taskstatus')),
                ('tasks', models.ManyToManyField(blank=True, related_name='project_tasks', to='tasks.maintask')),
            ],
            options={
                'verbose_name': 'Main task',
                'verbose_name_plural': 'Main tasks',
            },
        ),
    ]
